---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:humberdevops/question6
    path: charts
    ref: master
  values:
    image:
      repository: jancilm/webimage
      tag: latest
    replicaCount: 1
    hpa:
      enabled: false